# Generated by Django 3.1 on 2020-09-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0002_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(choices=[('mikrotik', 'Mikrotik'), ('cisco', 'Cisco'), ('ransnet', 'Ransnet')], max_length=255),
        ),
    ]
